on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm i
    - run: npm publish
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
